/* eslint-disable comma-dangle */
// module.exports = {
//   CbiBar: { ./src: './src/packages/bar/index.js', dist: 'lib/bar' },
//   CbiHistogram: { ./src: './src/packages/histogram/index.js', dist: 'lib/histogram' },
//   CbiFunnel: { ./src: './src/packages/funnel/index.js', dist: 'lib/funnel' },
//   CbiLine: { ./src: './src/packages/line/index.js', dist: 'lib/line' },
//   CbiPie: { ./src: './src/packages/pie/index.js', dist: 'lib/pie' },
//   CbiRing: { ./src: './src/packages/ring/index.js', dist: 'lib/ring' },
//   CbiRadar: { ./src: './src/packages/radar/index.js', dist: 'lib/radar' },
//   CbiWaterfall: { ./src: './src/packages/waterfall/index.js', dist: 'lib/waterfall' },
//   CbiIndex: { ./src: './src/packages/index/index.js', dist: 'lib/index' },
//   CbiChart: { ./src: './src/packages/chart/index.js', dist: 'lib/chart' },
//   CbiMap: { ./src: './src/packages/map/index.js', dist: 'lib/map' },
//   CbiBmap: { ./src: './src/packages/bmap/index.js', dist: 'lib/bmap' },
//   CbiAmap: { ./src: './src/packages/amap/index.js', dist: 'lib/amap' },
//   CbiSankey: { ./src: './src/packages/sankey/index.js', dist: 'lib/sankey' },
//   Cbiheatmap: { ./src: './src/packages/heatmap/index.js', dist: 'lib/heatmap' },
//   CbiScatter: { ./src: './src/packages/scatter/index.js', dist: 'lib/scatter' },
//   CbiCandle: { ./src: './src/packages/candle/index.js', dist: 'lib/candle' },
//   CbiGauge: { ./src: './src/packages/gauge/index.js', dist: 'lib/gauge' },
//   CbiTree: { ./src: './src/packages/tree/index.js', dist: 'lib/tree' },
//   CbiLiquidfill: { ./src: './src/packages/liquidfill/index.js', dist: 'lib/liquidfill' },
//   CbiWordcloud: { ./src: './src/packages/wordcloud/index.js', dist: 'lib/wordcloud' }
// }
module.exports = {
  CbiBarChart: './src/packages/bar/index.js',
  CbiHistogramChart: './src/packages/histogram/index.js',
  CbiPercentStackChart: './src/packages/percentStack/index.js',
  CbiFunnelChart: './src/packages/funnel/index.js',
  CbiLineChart: './src/packages/line/index.js',
  CbiPieChart: './src/packages/pie/index.js',
  CbiRingChart: './src/packages/ring/index.js',
  CbiRadarChart: './src/packages/radar/index.js',
  CbiWaterfallChart: './src/packages/waterfall/index.js',
  CbiIndexChart: './src/packages/index/index.js',
  CbiChartChart: './src/packages/chart/index.js',
  CbiMapChart: './src/packages/map/index.js',
  // CbiBmapChart: './src/packages/bmap/index.js',
  // CbiAmapChart: './src/packages/amap/index.js',
  CbiSankeyChart: './src/packages/sankey/index.js',
  CbiheatmapChart: './src/packages/heatmap/index.js',
  CbiScatterChart: './src/packages/scatter/index.js',
  CbiCandleChart: './src/packages/candle/index.js',
  CbiGaugeChart: './src/packages/gauge/index.js',
  CbiTreeChart: './src/packages/tree/index.js',
  CbiLiquidfillChart: './src/packages/liquidfill/index.js',
}
